# module: this module
# dependent-module: self and modules that self dependent on
# dependence-module: self and modules dependent on this module
# related-module: self, modules that self dependent on and modules dependent on this module
rules:
- patterns:
  - .azure-pipeline/*
  - NugGet.Config
  - Repo.props
  steps:
  - build:all
  - breaking-change:all
  - dependence:all
  - help:all
  - signature:all
  - test:all
  - sub-task:all
- patterns:
  - src/*.props
  steps:
  - build:all
  - dependence:all
  - test:all
- patterns:
  - src/lib/*
  steps:
  - build:all
  - dependence:all
- patterns:
  - docker/*
  - .github/*
  - setup/*
  - .dockerignore
  - .git*
  - appveyor.yml
  - CONTRIBUTION.md
  - LICENSE.txt
  - README.md
  - '**/ChangeLog.md'
  - '**/readme.md'
  - src/**/document/*
  steps: []
- patterns:
  - src/{ModuleName}/test/*
  - src/{ModuleName}/*.Test/*
  steps:
  - build:dependent-module
  - test:module
- patterns:
  - src/{ModuleName}/**/*.md
  steps:
  - build:module
  - help:module
- patterns:
  - src/{ModuleName}/**/*.csproj
  steps:
  - build:related-module
  - dependence:dependence-module
  - test:dependence-module
- patterns:
  - src/{ModuleName}/*
  steps:
  - build:related-module
  - breaking-change:module
  - help:module
  - signature:module
  - test:dependence-module
- patterns:
  - tools/StaticAnalysis/Exceptions/{ModuleName}/MissingAssemblies.csv
  - tools/StaticAnalysis/Exceptions/{ModuleName}/AssemblyVersionConflict.csv
  - tools/StaticAnalysis/Exceptions/{ModuleName}/ExtraAssemblies.csv
  - tools/StaticAnalysis/Exceptions/{ModuleName}/SharedAssemblyConflict.csv
  steps:
  - build:module
  - dependence:module
- patterns:
  - tools/StaticAnalysis/Exceptions/{ModuleName}/BreakingChangeIssues.csv
  steps:
  - build:module
  - breaking-change:module
- patterns:
  - tools/StaticAnalysis/Exceptions/{ModuleName}/HelpIssues.csv
  steps:
  - build:module
  - help:module
- patterns:
  - tools/StaticAnalysis/Exceptions/{ModuleName}/SignatureIssues.csv
  steps:
  - build:module
  - signature:module
- patterns:
  - tools/StaticAnalysis/*
  - tools/Tools.Common/*
  steps:
  - build:all
  - breaking-change:all
  - dependence:all
  - help:all
  - signature:all
- patterns:
  - tools/Az.Tools.Predictor/*
  steps:
  - sub-task:Predictor
- patterns:
  - tools/Az.Tools.Installer/*
  steps:
  - sub-task:Installer
- patterns:
  - tools/AddModulePsm1Dependency.ps1
  - tools/Common.Netcore.Dependencies.targets
  - tools/AzureRM.Example.psm1
  steps:
  - build:all
  - breaking-change:all
  - dependence:all
  - help:all
  - signature:all
  - test:all
- patterns:
  - tools/GenerateHelp.ps1
  - tools/HelpGeneration/*
  steps:
  - build:all
  - help:all
- patterns:
  - tools/CheckAssemblies.ps1
  steps:
  - build:all
  - dependence:all
- patterns:
  - tools/CheckSignature.ps1
  steps:
  - build:all
  - signature:all
- patterns:
  - tools/Common.Netcore.Dependencies.Test.targets
  steps:
  - build:all
  - test:all
- patterns:
  - tools/ARMIncrementVersion.ps1
  - tools/ARMSyncVersion.ps1
  - tools/ASMIncrementVersion.ps1
  - tools/AzureRM.Example.psm1
  - tools/BuildInstaller.ps1
  - tools/CheckChangeLog.ps1
  - tools/CheckIgnoredFile.ps1
  - tools/CleanupBuild.ps1
  - tools/CommonIncrementVersion.ps1
  - tools/CreateAliasMapping.ps1
  - tools/CreateFilterMappings.ps1
  - tools/CreateMappings_rules.json
  - tools/CreateMappings.ps1
  - tools/CreateRegistryEntry.ps1
  steps: []
- patterns:
  - tools/Az/*
  - tools/BatchModelGenerator/*
  - tools/BreakingChanges/*
  - tools/Docker/*
  - tools/FormatPs1XmlGenerator/*
  - tools/Gen2Master/*
  - tools/InstallationTests/*
  - tools/Installer/*
  - tools/NetCoreCsProjSync/*
  - tools/NetCorePsd1Sync/*
  - tools/ProjectTemplates/*
  - tools/RepoTasks/*
  - tools/SecurityTools/*
  - tools/Test/*
  - tools/Tools.Common.Test/*
  - tools/VersionController/*
  steps: []
- patterns:
  - others
  steps:
  - build:all
  - breaking-change:all
  - dependence:all
  - help:all
  - signature:all
  - test:all
